on:
  push:
    branches:
      - master
  pull_request:

name: Run unit tests

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu Latest GCC, coverage enabled", 
            os: ubuntu-latest,
            cov: true
          }
        - {
            name: "macOS Latest Clang", 
            os: macos-latest,
            cov: false
          }

    steps:
    - uses: actions/checkout@v4

    - name: Get latest CMake
      uses: lukka/get-cmake@latest

    - name: Configure the build
      if: ${{ matrix.config.cov == false }}
      run: cmake -S . -B build

    - name: Configure the build with coverage
      if: ${{ matrix.config.cov == true }}
      run: cmake -S . -B build -DCODE_COVERAGE=ON

    - name: Run the build
      run: cmake --build build

    - name: Run the tests
      run: |
        cd build
        # Avoid using ctest because it's so slow; it starts a
        # new process for each individual test, which is crazy.
        for exe in $(ctest --show-only=json-v1 | jq -r ".tests[] | .command | .[0]"  | sort | uniq)
        do
            echo "#### RUNNING ${exe} ####"
            echo 
            ${exe} --gtest_brief=1
            echo
        done 

    - name: Generate code coverage
      if: ${{ matrix.config.cov == true }}
      run: |
        cd build/tests/CMakeFiles/libtest.dir/src/
        gcov -abcfu *.gcno

    - name: Upload to Codecov
      if: ${{ matrix.config.cov == true }}
      uses: codecov/codecov-action@v4
      with:
        directory: build/tests/CMakeFiles/libtest.dir/src/
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
